/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e4e0d8",
        "tertiary-fixed-dim": "#dcc48e",
        "secondary-container": "#f0e8db",
        "primary-fixed-dim": "#8ecf9e",
        "surface-container-high": "#eae6de",
        error: "#b83230",
        "surface-tint": "#4a7c59",
        "on-secondary": "#ffffff",
        secondary: "#5a685e",
        surface: "#faf6f0",
        "on-surface": "#212b23",
        "on-primary-fixed-variant": "#2a6038",
        "on-secondary-container": "#5e5548",
        primary: "#4a7c59",
        "primary-hover": "#3b6347",
        "outline-variant": "#e2ded5",
        "surface-container": "#f5f0e6",
        background: "#faf6f0",
        "on-primary-container": "#d8f0de",
        "on-surface-variant": "#5a685e",
        "inverse-surface": "#212b23",
        "primary-fixed": "#c8e8d0",
        "primary-container": "#78a886",
        outline: "#74796e",
        "on-primary-fixed": "#002110",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#d4ccbf",
        "tertiary-container": "#c4a66a",
        "surface-bright": "#faf6f0",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#f0e8db",
        "on-background": "#212b23",
        "inverse-primary": "#8ecf9e",
        "on-tertiary-container": "#554020",
        "surface-container-low": "#faf6f0",
        "on-tertiary-fixed-variant": "#554020",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#1e1a13",
        "on-tertiary-fixed": "#221a05",
        "surface-dim": "#eae4d8",
        "tertiary-fixed": "#f8e0a8",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#eae4d8",
        tertiary: "#705c30",
        "tertiary-dark": "#5e4d26",
        hairline: "#e2ded5",
        "hairline-dark": "#d5cebe",
      },
      fontFamily: {
        headline: ["Literata", "Georgia", "serif"],
        display: ["Literata", "Georgia", "serif"],
        body: ["Nunito Sans", "sans-serif"],
        label: ["Nunito Sans", "sans-serif"],
        serif: ["Literata", "Georgia", "serif"],
        sans: ["Nunito Sans", "sans-serif"],
      },
      boxShadow: {
        "terra-card": "0 4px 20px rgba(46, 50, 48, 0.06)",
        "terra-hover": "0 10px 30px rgba(74, 124, 89, 0.12)",
      },
    },
  },
  plugins: [],
};
